name: "CI"
on:
  push:
  pull_request:
jobs:
  Nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nixbuild/nix-quick-install-action@v21
        with:
          nix_conf: |
            experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v12
        with:
          name: nammayatri
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Download from Nix cache + build external deps
        run: |
          nix develop -j 4 -c echo
      - name: Build all packages 🔨
        id: build-nix
        run: |
          nix build -L 
      - name: Flake checks 🧪
        run: |
          # Because 'nix flake check' is not system-aware
          # See https://srid.ca/haskell-template/checks
          nix run nixpkgs#sd \
            'systems = nixpkgs.lib.systems.flakeExposed' \
            'systems = [ "x86_64-linux" ]' \
            flake.nix

          # Sandbox must be disabed for:
          # https://github.com/srid/haskell-flake/issues/21
          nix \
            --option sandbox false \
            flake check -L
